### ISSUE TITLE
Issue with phoenix umbrella app

### ISSUE THREAD

**Issue by vivialima** [sticksnleaves/bamboo_eex#2]
Hi everyone

We are developing an umbela project with 2 apps: domain and web.

The emails are at domain layer and the controllers call them. The issue is the templates `path`. We had tried use absolute path and relative path but both didn't work.

Attemps:
- `use Bamboo.EEx, path: 'apps/app_name/lib/app_name/mail_templates'`
The app works as well, but the tests fail because they couldn't find the template files

- `use Bamboo.EEx, path: 'lib/app_name/mail_templates'`
Only the domain tests works, executing the tests into its folder

- `use Bamboo.EEx, path: 'Path.expand("../app_name/lib/project/mail_templates")'`
The app works at development and test, but it fails on production, template not found.

```
could not read file "/tmp/build_3432432/apps/app_name/lib/app_name/mail_templates/forgot_password.html.eex": no such file or directory
```

Is there a way to fix it?

Thank you

**Comment by anthonator** [comment]
Are you using something like distillery in production? If that's the case you might be able to do something similar to attempt 3 using [Application.app_dir/2](https://hexdocs.pm/elixir/Application.html#app_dir/2) to get the proper path to your child application.

```
use Bamboo.EEx, path: Application.app_dir(:domain, "lib/project/mail_templates")
```

**Comment by vivialima** [comment]
Thanks for the reply! 😄 

Not works using `Application.app_dir` . The path in production remains with `tmp..` and not found the template file. We solved using this solution as a reference -> https://elixirforum.com/t/is-it-possible-to-include-resource-files-when-packaging-my-project-using-mix-escript/730

**Comment by anthonator** [comment]
Great! I'm glad you were able to get this solved.
